### ISSUE TITLE
Extending "small-order element" term with "non-canonical encoding"

### ISSUE THREAD

**Issue by Frosne** [WICG/webcrypto-secure-curves#32]
The specification currently states "If the key data of key represents an invalid point or a small-order element on the Elliptic Curve of Ed25519, return false. "

Should we change "small-order element" to "small-order element (including non-canonical representation)"? Just to make it clearer. For instance, in [tests](https://searchfox.org/mozilla-central/source/testing/web-platform/tests/WebCryptoAPI/sign_verify/eddsa_vectors.js#160) there is a distinction between small order and small order (non-canonical).

**Comment by Frosne** [comment]
As an important bit against my proposal is this modification would make the understanding a bit more complicated and specific. Maybe the developers do not need to trouble themselves with the EC specificity?

**Comment by twiss** [comment]
> Maybe the developers do not need to trouble themselves with the EC specificity?

To be fair, the same argument could be made against having the language for small-order checks in the Web Crypto spec at all :) TBH all of it really belongs in the IETF spec. That being said, since the language to reject non-canonical points is already there in RFC 8032 (sections [5.1.3](https://www.rfc-editor.org/rfc/rfc8032.html#section-5.1.3) and [5.2.3](https://www.rfc-editor.org/rfc/rfc8032.html#section-5.2.3), step 1 say "If the resulting value is >= p, decoding fails."), I would prefer not to duplicate it unnecessarily (unlike the small-order check which is not specified in RFC 8032).

**Comment by Frosne** [comment]
ok!
